services:
    cms.block.ckeditor:
        class: Th3Mouk\CMSPageBundle\Block\CKEditorBlockService
        arguments: ['cms.block.ckeditor', "@templating"]
        tags:
            - { name: sonata.block }

    cms.block.migrate:
        class: Th3Mouk\CMSPageBundle\Migration\BlocksMigration
        arguments: ['@sonata.page.manager.block']
