services:
    cms.block.contenu.ckeditor:
        class: Th3Mouk\CMSPageBundle\Block\ContenuCKEditor
        arguments: ['Bloc Contenu CKEditor', @templating]
        tags:
            - { name: sonata.block }
