language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.0
      env: SYMFONY_VERSION=2.3.*
    - php: 7.0
      env: SYMFONY_VERSION=2.7.*
    - php: 5.5
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*
    - php: nightly
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=3.0.*
    - php: 7.0
      env: SYMFONY_VERSION=3.1.*

  allow_failures:
    - php: nightly
    - env: SYMFONY_VERSION=3.0.*
    - env: SYMFONY_VERSION=3.1.*

before_install:
  - (phpenv config-rm xdebug.ini || exit 0)

before_script:
  - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d && echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - export PATH=$HOME/.local/bin:$PATH
  - travis_wait composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
